version: '3.8'

services:
  modern-images:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: modern-images
    restart: unless-stopped
    depends_on:
      - redis
    
    # 网络配置
    ports:
      - "3000:3000"
    networks:
      - app-network
    
    # 环境变量
    environment:
      - NODE_ENV=production
      - PORT=3000
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - REDIS_URL=redis://redis:6379
    
    # 卷挂载 - 使用绑定挂载以避免权限问题
    volumes:
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: modern-images-redis
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

# 网络配置
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 卷配置
volumes:
  uploads_data:
    driver: local
  redis_data:
    driver: local
  session_secret:
    driver: local

# Secrets（需要在生产环境中使用Docker Swarm或外部secrets管理）
secrets:
  session_secret:
    external: true 